name: transactions
version: 0.1.0
config-version: 2
profile: transactions
model-paths: ["models"]
macro-paths: ["macros"]
models:
  transactions:
    +file_format: iceberg
    silver:
      +schema: silver
    gold:
      +schema: gold
